### ISSUE TITLE
How large can arrays be?

### ISSUE THREAD

**Issue by anywhichway** [YuJianrong/fast-array-diff#135]
I have arrays of lengths92054 89384 29287 68962 61669 containing just integers. 

This code never returns:

```
    .add("diff.diff",() => {
        let result = diff.diff([arg1,arg2,arg3,arg4,arg5]).added;
        size = result.length;
    })
```

This code does return using short arrays:

```
.add("diff.diff short",() => {
        const arg1 =[1,2], arg2 = [1,2,3];
        let result = diff.diff([arg1,arg2]).added;
        size = result.length;
    })
```

As does this using a different library and the original long arrays:

```
add("difference",() => {
    const result = arg1.difference(arg2,arg3,arg4,arg5);
    size = result.length;
})
```

**Comment by Jianrong-Yu** [comment]
Are you using TypeScript? The syntax of function `diff` is:
```Typescript
function diff<T>(
  a: T[],
  b: T[],
  compareFunc: (ia: T, ib: T) => boolean = (ia: T, ib: T) => ia === ib,
): DiffData<T>
```
You should get a compiling error if you use Typescript since you use it in a wrong way.
In both `diff.diff([arg1,arg2,arg3,arg4,arg5])` and `diff.diff([arg1,arg2])` there is only one parameter for function `diff`.

**Comment by Jianrong-Yu** [comment]
How large the array can be supported is depend on the array, the time complexity of this algorithm is O(ND) (refer: http://www.xmailserver.org/diff2.pdf), if `D`(the difference between two arrays) is small it's possible to support a large `N` (large array), otherwise if the difference is huge between arrays the time complexity will be O(N^2) which may not work in any array longer then 10^4 items.

**Comment by anywhichway** [comment]
Thanks for quick response. I do not use TypeScript. I will try an alternate call with diff(array,array).

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
