### ISSUE TITLE
diff function returning added and removed values when there aren't any

### ISSUE THREAD

**Issue by alexandrulesi** [YuJianrong/fast-array-diff#96]
I'm trying to speed up our existing code using the `diff` function by replacing 

```js
	const factorSetsToArchive = existingFactorSets.filter(
		(existingFactorSet) => !newFactorSets.find((newFactorSet) => areFactorSetsEqual(existingFactorSet, newFactorSet))
	);
	const factorSetsToCreate = newFactorSets.filter(
		(factorSet) => !existingFactorSets.find((existingFactorSet) => areFactorSetsEqual(existingFactorSet, factorSet))
	);
```

with 

```js
	const { added: factorSetsToCreate, removed: factorSetsToArchive } = diff(
		existingFactorSets,
		newFactorSets,
		areFactorSetsEqual
	);
```

Using our original code I am getting empty arrays for both `factorSetsToArchive` and `factorSetsToCreate`.  Using the `diff` function I am getting values in there. The values looked identical to me so I picked a sample from each list and ran the compare function `areFactorSetsEqual` on them, which returned true. So they shouldn't have been in that list to begin with. Looks to me like there might be a bug.

If you need more info I can share the comparator function, but I can't share any actual data since it is licensed. The function doesn't seem to be causing the issue though.

**Comment by YuJianrong** [comment]
This library is used to get the diff between two `sequences`: it means `ABCD` is different to `ACBD`. In your old code, it's just a filter for the removed/created items in the `sets`, so you should not use this library in your case.

I suggest you create a hash function for your `FactorSet` and put them into an ES `Set`, you can do the two functions in O(n) time complicity instead of O(n^2).

**Comment by alexandrulesi** [comment]
Oh thanks for clarifying! I had something similar in mind but I'm still hoping to find a solution somewhere and avoid implementing something myself.
